# C\u1ea5u h\u00ecnh k\u1ebft n\u1ed1i SQL Server (Nh\u1edb \u0111\u1ed5i t\u00ean DB, username, password cho kh\u1edbp m\u00e1y b\u1ea1n)
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=ShoesOnlineShop;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Hibernate kh\u00f4ng t\u1ef1 \u0111\u1ed9ng t\u1ea1o b\u1ea3ng n\u1eefa (v\u00ec b\u1ea1n \u0111\u00e3 c\u00f3 file SQL ch\u1ea1y tay r\u1ed3i)
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect